[package]
name = "tests_executor_rust"
version = "3.2.3"
authors = ["Laurent Wouters <lwouters@cenotelie.fr>"]
description = "Executor for tests for the Hime Parser Generator in Rust."
homepage = "https://cenotelie.fr/hime"
repository = "https://bitbucket.org/cenotelie/hime"
keywords = ["hime", "parser", "generator", "lr", "glr", "rnglr"]
categories = ["algorithms", "parsing", "parser-implementations", "text-processing"]
license = "LGPL-3.0"

[dependencies]
hime_redist = "3.2.3"
libloading = "0.4.3"

[patch.crates-io]
hime_redist = { path = "../runtime-rust" }